---
title: "Mini-Project 3"
author: "Emma Livingston"
date: "November 13, 2017"
output: html_document
---

```{r setup, include=FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include = FALSE, message = FALSE}
library(mdsr)
library(RMySQL)
library(tidyverse)
db <- dbConnect_scidb(dbname = "imdb")
```

##Genre Multiplicity

In this project, we looked at 


```{r}
num_genres <- db %>%
  dbGetQuery("SELECT title.title, title.id, production_year, info, sum(1) AS N
FROM movie_info
JOIN title ON title.id = movie_info.movie_id
WHERE info_type_id = 3 AND kind_id = 1
GROUP BY title.id
ORDER BY title, title.id;")
#This query makes use of the index on info_type_id in the movie_info table
```

```{r}
num_year <- db %>%
  dbGetQuery("SELECT production_year, info, sum(1) AS N
FROM movie_info
JOIN title ON title.id = movie_info.movie_id
WHERE info_type_id = 3 AND kind_id = 1
GROUP BY production_year
ORDER BY title, title.id;")
#This query also uses the index on the info_type_id in the movie_info table
```

```{r}
joined <- num_genres %>%
  inner_join(num_year, by = "production_year") %>%
  filter(production_year <= 2026) %>%
  group_by(production_year) %>%
  summarize(avg_genres = mean(N.x))
#Here we combined the resulting tables from the above queries, filtered out any film with a production year greater than 2026 (because of the \href{http://www.imdb.com/title/tt5174640/}{film to be released in 2115}), and found the average number of genres.
```

```{r}
ggplot(data = joined, aes(x = production_year, y = avg_genres)) +
  geom_line(size = 1.2) +
  geom_vline(xintercept = 2017, col = "blue", linetype = 2) +
  geom_text(aes(label = "2017", x = 2012, y = 3.5)) +
  geom_vline(xintercept = 1947, col = "blue", linetype = 2) +
  geom_text(aes(label = "1947", x = 1942, y = 3.5)) +
  ylab("Average Number of Genres per Movie") +
  xlab("Production Year")
```


GitHub Repository: https://github.com/emmal73/mp3